# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker|
    docker.vagrant_vagrantfile = "../Vagrantfile"
    docker.image = "peerchemist/peercoind:pars"
    docker.ports = ['9902:9902']
    docker.name = 'pars'
    docker.cmd = ['-rpcallowip=*', '-rpcpassword=bar', '-rpcuser=foo']
  end
end
