# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker|
    docker.vagrant_vagrantfile = "../Vagrantfile"
    docker.image = "peerchemist/peercoind:pars"
    docker.ports = ['9904:9904']
    docker.name = 'parstestnet'
    docker.cmd = ['-rpcallowip=*', '-rpcpassword=bar', '-rpcuser=foo', '-testnet=1']
  end
end
